#ifndef SHL_DEFS_H
#define SHL_DEFS_H

enum SHLPlayerState
{
	SHL_PLAYERSTATE_NORMAL = 0,
	SHL_PLAYERSTATE_STIMULATED,
	SHL_PLAYERSTATE_GROUNDED,
	SHL_PLAYERSTATE_TRAMPLED,
	SHL_PLAYERSTATE_GRABBED,
	SHL_PLAYERSTATE_ACTIVE_SCENE,
	SHL_PLAYERSTATE_CLIMAX_LOCKED,
	SHL_PLAYERSTATE_DEFEAT_MENU,
	SHL_PLAYERSTATE_DEFEAT_SCENE,
	SHL_PLAYERSTATE_RECOVERY
};

const char* SHL_PlayerStateName(int state);

#endif // SHL_DEFS_H